runtime:  python37

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  CLOUD_SQL_USERNAME: username
  CLOUD_SQL_PASSWORD: password
  CLOUD_SQL_DATABASE_NAME: dbname
  CLOUD_SQL_CONNECTION_NAME: capstone:region:instancename


