runtime:  python37

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  CLOUD_SQL_USERNAME: mysql.sys
  CLOUD_SQL_PASSWORD: congon
  CLOUD_SQL_DATABASE_NAME: chainedsurveyapp
  CLOUD_SQL_CONNECTION_NAME: capstone-312002:us-central1:surveyinstance


